apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bo3jhu7qu-java-springboot 
  janus-idp.io/tekton: bo3jhu7qu-java-springboot
  backstage.io/kubernetes-id: bo3jhu7qu-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bo3jhu7qu-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml